### ISSUE TITLE
[BUG] Hook attached to despawning titan

### ISSUE THREAD

**Issue by rc174945** [AoTTG-2/Aottg2-Unity4#26]
Hooks teleport when they are attached to a despawning titan. Either despawn the hook when the titan despawns, or keep it in the same location afterwards without teleporting. The former is more tricky to do correctly so keeping the hook from teleporting is sufficient for now.

**Comment by KarinGaDayo** [comment]
Is there a character state transition when the character is reaching the target?
I used the old version and found that when the Titan fell down and disappeared, the hook was positioned where the Titan would have been in its normal state。It feels like when the hook hooks onto the object, it creates a position in the child object of the object, which changes position according to the Titan.
Try to remove the hook position before the Titan fall state ends，Is it a likely way to succeed?

**Comment by rc174945** [comment]
the bug occurs because in the Characters/Human/Hook class we don't update _lastWorldHookPosition variable. It is only set when we first hook the titan so if it moves before dying the hook will teleport back to the old position.
